monlog/log/api/urls.py
from django.conf.urls.defaults import patterns, include, url
from tastypie.api import Api
from monlog.log.api.api import LogResource
from monlog.log.api.api import LogCollectionResource
from monlog.log.api.api import ExpectationCollectionResource

log_resource = LogResource()
log_collection = LogCollectionResource()
expectation_collection = ExpectationCollectionResource()

urlpatterns = patterns('',
    url(r'^', include(log_resource.urls)),   # API available with POST
    url(r'^', include(log_collection.urls)), # API available from GET
    url(r'^', include(expectation_collection.urls)),
)

monlog/urls.py
from django.conf.urls.defaults import patterns, include, url
from tastypie.api import Api
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'monlog.log.views.list', {'label_name' : None}),
    url(r'^api/', include('monlog.log.api.urls')),
    url(r'^label/save/', 'monlog.log.views.save_label'),
    url(r'^label/delete/(?P<label_name>.+)', 'monlog.log.views.delete_label'),
    url(r'^label/(?P<label_name>.+)', 'monlog.log.views.list'),

    url(r'^expectation/add/', 'monlog.log.views.expectation'),
    url(r'^expectation/save/', 'monlog.log.views.save_expectation'),
    url(r'^expectation/delete/(?P<exp_name>.+)', 'monlog.log.views.delete_expectation'),
    url(r'^expectation/(?P<exp_name>.+)', 'monlog.log.views.expectation'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'template_name': 'login.html' }),

    url(r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

monlog/log/models.py
from django.contrib.auth.models import User
from django.db import models
from tastypie.models import create_api_key
from django.http import QueryDict
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tastypie.utils import dict_strip_unicode_keys

models.signals.post_save.connect(create_api_key, sender=User)

SEVERITY_CHOICES = (
                    (0, 'debug'),
                    (1, 'info'),
                    (2, 'notify'),
                    (3, 'warning'),
                    (4, 'error'),
                    (5, 'critical'),
                    (6, 'alert'),
                    (7, 'emergency')
                   )

class LogMessage(models.Model):
    """
    Model of a log message
    """

    severity = models.IntegerField(choices=SEVERITY_CHOICES)
    datetime = models.DateTimeField()
    add_datetime = models.DateTimeField(auto_now_add=True)
    server_ip = models.GenericIPAddressField()
    application = models.ForeignKey(User)
    short_desc = models.CharField(max_length=100)
    long_desc = models.TextField()

    def __unicode__(self):
        return self.short_desc

    def pretty_severity(self):
        """
        Return the string name of this log message severity.
        """
        return SEVERITY_CHOICES[self.severity][1]

    class Meta:
        ordering = ('-datetime',)



class Filter(models.Model):
    """
    Model of a search filter. This is used in expectations and labels.
    """

    class Meta:
        abstract = True

    query_string = models.TextField()

    def __unicode__(self):
        return self.query_string

    def get_dict(self):
        """
        Creates a ``QueryDict`` from the querystring of this label.
        """
        return QueryDict(self.query_string)

class Label(Filter):
    """
    Model for labels.
    """
    user = models.ForeignKey(User)
    label_name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.label_name

    class Meta:
        unique_together = ('user','label_name')


class RelativedeltaField(models.Field):

    description = "A relative timedelta"

    __metaclass__ = models.SubfieldBase

    def db_type(self, connection=None):
        """
        Current representation of RelativedeltaField in the database.
        """
        return 'char(30)'

    def to_python(self, value):
        """
        Creates a relativedelta object from what we get from the database.
        """
        if not value:
            return None
        if isinstance(value, (str, unicode)):
            #raises ValueError if split not possible.
            years, months, days, hours, minutes = [int(v)
                                                   for v
                                                   in value.split("_")]
            return relativedelta(years   = years,
                                 months  = months,
                                 days    = days,
                                 hours   = hours,
                                 minutes = minutes)

        elif isinstance(value, relativedelta):
            return value
        else:
            return None

    def get_db_prep_value(self, value, connection=None, prepared=False):
        """
        Concatenate unit and timedelta into a string.
        """
        return "%i_%i_%i_%i_%i" % (value.years,
                                   value.months,
                                   value.days,
                                   value.hours,
                                   value.minutes)

    def formfield(self, **kwargs):
        """
        Using a RelativedeltaField to represent this field in a form.
        """
        from monlog.log.forms import RelativedeltaField as RelativedeltaFormField
        defaults = { 'form_class' : RelativedeltaFormField }
        defaults.update(kwargs)
        return super(RelativedeltaField, self).formfield(**defaults)

    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return self.get_db_prep_value(value)


class Expectation(Filter):
    """
    Model for expectations.
    """

    name = models.CharField(max_length=20)
    user             = models.ForeignKey(User)

    # timestamp for original deadline
    deadline          = models.DateTimeField()
    original_deadline = models.DateTimeField()


    # +- tolerance in relative delta
    # example: '+- 10 minute'
    tolerance = RelativedeltaField()

    # repeat every ``repeat`` relative delta
    # example: 'every 2 month'
    repeat       = RelativedeltaField()
    repeat_count = models.IntegerField()

    least_amount_of_results = models.IntegerField()

    class Meta:
        unique_together = ('name', 'user')

    def __unicode__(self):
        return self.name

    def apply_tolerance(self, querydict):
        """
        Applies startdate and enddate to a querydict.

        Startdate = Current Deadline - Tolerance
        Enddate   = Current Deadline + Tolerance
        """
        if self.deadline is None:
            print ("Error: Deadline must've been set before "
                   "applying tolerance to query string.")
            return querydict

        startdate = (self.deadline - self.tolerance)
        enddate   = (self.deadline + self.tolerance)

        querydict['datetime__gte'] = startdate.isoformat()
        querydict['datetime__lte'] = enddate.isoformat()
        return querydict

    def check_expectation(self):
        """
        Checks if X amount of log messages matches the filter.
        X is the least amount of log messages we need in order to accept
        the expectation.

        Returns a dict of errors and the queryset. If no errors was found
        an empty dict will be returned.
        """
        errors = {}
        qd = dict_strip_unicode_keys(QueryDict(self.query_string,mutable=True))
        qd = self.apply_tolerance(qd)
        qs = LogMessage.objects.filter(**qd)
        if len(qs) < self.least_amount_of_results:
            errors['not_enough_results'] = (
                "Not enough results found. Found:\"" +
                str(len(qs)) + "\" out of \"" +
                str(self.least_amount_of_results) + "\".")
        return (errors, qs)

    @property
    def next_deadline(self):
        """
        Returns next deadline as a datetime object.
        Does NOT change the deadline.
        """
        return self.original_deadline + \
               self.repeat * self.repeat_count


class ExpectationMessage(LogMessage):
    """
    A message that monlog creates to log expectations.
    """

    expectation = models.ForeignKey(Expectation, on_delete=models.SET_NULL,
                                    blank=True, null=True)

monlog/log/views.py
# coding=utf8

from django.http import HttpResponse, HttpResponseBadRequest, QueryDict, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.decorators import login_required
from models import LogMessage, Label, Expectation, SEVERITY_CHOICES
from django.contrib.auth.models import User
from monlog.log.forms import LogQueryForm, LabelForm, ExpectationForm
from datetime import datetime
from dateutil.relativedelta import relativedelta
import logging

@login_required
def expectation(request, exp_name=None):
    """
    A view for editing expectations.
    """
    exp = None
    try:
        exp = Expectation.objects.get(name=exp_name, user=request.user)
    except Expectation.DoesNotExist:
        exp_name = None

    context = RequestContext(request)
    if exp is not None:
        context['eqf'] = ExpectationForm(exp.get_dict(), instance=exp)
    else:
        context['eqf'] = ExpectationForm()
    context['labels'] = Label.objects.filter(user=request.user)
    context['exp'] = exp

    context['active_expectation'] = exp_name
    context['expectations'] = Expectation.objects.filter(user=request.user)

    return render_to_response('expectation.html', context)

@login_required
def save_expectation(request):
    """
    Recieves a expectation form and creates an expectation from it. Redirects 
    to the expectation view afterwards.
    """

    dict = QueryDict(request.POST.get('query'),mutable=True)
    name                    = request.POST.get('name', None)

    deadline                = dict.pop('deadline')[0]

    tolerance_month         = int(dict.pop('tolerance_0')[0] or 0) or 0
    tolerance_day           = int(dict.pop('tolerance_1')[0] or 0) or 0
    tolerance_hour          = int(dict.pop('tolerance_2')[0] or 0) or 0
    tolerance_minute        = int(dict.pop('tolerance_3')[0] or 0) or 0

    repeat_month            = int(dict.pop('repeat_0')[0] or 0) or 0
    repeat_day              = int(dict.pop('repeat_1')[0] or 0) or 0
    repeat_hour             = int(dict.pop('repeat_2')[0] or 0) or 0
    repeat_minute           = int(dict.pop('repeat_3')[0] or 0) or 0

    tolerance = relativedelta(months  = tolerance_month,
                              days    = tolerance_day,
                              hours   = tolerance_hour,
                              minutes = tolerance_minute)
    repeat    = relativedelta(months  = repeat_month,
                              days    = repeat_day,
                              hours   = repeat_hour,
                              minutes = repeat_minute)

    if tolerance == relativedelta():
        return HttpResponseBadRequest('Need a tolerance')

    if repeat == relativedelta():
        return HttpResponseBadRequest('Need a repeat')

    least_amount_of_results = dict.pop('least_amount_of_results')[0]

    query_string = dict.urlencode()

    try:
        expectation = Expectation.objects.get(name=name, user=request.user)
        expectation.original_deadline       = deadline
        expectation.deadline                = deadline
        expectation.tolerance               = tolerance
        expectation.repeat                  = repeat
        expectation.repeat_count            = 0
        expectation.least_amount_of_results = least_amount_of_results
        expectation.query_string            = query_string
    except Expectation.DoesNotExist:
        expectation = Expectation(
            user                    = request.user,
            name        = name,
            deadline                = deadline,
            original_deadline       = deadline,
            tolerance               = tolerance,
            repeat                  = repeat,
            repeat_count            = 0,
            least_amount_of_results = least_amount_of_results,
            query_string            = query_string)

    expectation.save()
    return HttpResponse('/expectation/'+name)

def delete_expectation(request, exp_name):
    """
    Used when a user deletes an expectation
    """

    try:
        expectation = Expectation.objects.get(name=exp_name, user=request.user)
        expectation.delete()
    except Expectation.DoesNotExist:
        pass

    return HttpResponseRedirect('/')

@login_required
def list(request, label_name):
    """
    View for listing all log messages. Labels are used to filter which messages
    are displayed.
    """

    # Create a default LogQueryForm which is used if no label is specified.
    qd = QueryDict('', mutable=True)
    lqf = None

    # Get label if user specified one.
    label_id = None
    if label_name:
        try:
            label = Label.objects.get(label_name=label_name, user=request.user)
            lqf = LogQueryForm(label.get_dict())
            label_id = label.id
        except Label.DoesNotExist:
            label_name = None
    else:
        # Default is all severities checked, and order by datetime.
        qd.setlist('severity__in',
                   request.GET.getlist('severity__in',
                   [ x[0] for x in SEVERITY_CHOICES ]))
        qd.setlist('order_by',
                   request.GET.getlist('order_by', ['-datetime']))

        qd.update(request.GET)

    if lqf is None:
        lqf = LogQueryForm(qd)

    # Set context variables
    context = RequestContext(request)
    context['lqf'] = lqf
    context['labels'] = Label.objects.filter(user=request.user)
    context['label_field'] = LabelForm(label_name)
    context['active_label'] = label_name
    context['expectations'] = Expectation.objects.filter(user=request.user)
    return render_to_response('list.html', context)

@login_required
def save_label(request):
    """
    Used when a user saves a new label.
    """

    name = request.POST.get('name')
    query_string = request.POST.get('query_string')

    # Look for required fields
    if not name:
        logging.debug("Name not defined")
        return HttpResponseBadRequest("Required fields: name, query_string")
    if not query_string:
        logging.debug("Query_String not defined")
        return HttpResponseBadRequest("Required fields: name, query_string")

    # Look if label name already exists, overwrite it if it does.
    try:
        label = Label.objects.get(label_name=name, user=request.user)
        label.query_string=query_string
    except Label.DoesNotExist:
        label = Label(user=request.user,
                      label_name=name,
                      query_string=query_string)
    label.save()
    return HttpResponse('/label/'+name)

@login_required
def delete_label(request, label_name):
    """
    Used when a user deletes a label
    """

    try:
        label = Label.objects.get(label_name=label_name, user=request.user)
        label.delete()
    except Label.DoesNotExist:
        pass

    return HttpResponseRedirect('/')

monlog/log/templates/base.html
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Monlog</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=480,user-scalable=false">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

    <link href="{{ STATIC_URL }}lib/bootstrap/less/bootstrap.less" rel="stylesheet/less" type="text/css">
    <link href="{{ STATIC_URL }}less/monlog.less" rel="stylesheet/less" type="text/css">
    <link href="{{ STATIC_URL }}lib/jquery/datetimepicker.css" rel="stylesheet" type="text/css">
    <link href="{{ STATIC_URL }}lib/jquery/jquery-ui.css" rel="stylesheet" type="text/css">

    {% compress js %}
    <!-- every JS file included inside this block will be compressed and concatenated to one file when DEBUG=False -->

    <script src="{{ STATIC_URL }}lib/less/dist/less-1.3.0.min.js" type="text/javascript"></script>

    <script src="{{ STATIC_URL }}lib/jquery/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}lib/jquery/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}lib/jquery/jquery-ui-timepicker-addon.js"></script>
    <script src="{{ STATIC_URL }}lib/jquery/jquery.appear-1.1.1.min.js"></script>

    <!-- Add all Bootstrap JS components separately since we include their repo as a submodule now -->
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap-typeahead.js"></script>

    <script src="{{ STATIC_URL }}lib/icanhaz/ICanHaz.min.js"></script>
    {% endcompress %}

 </head>

  <body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
              <a class="brand" href="/">Monlog</a>
              {% if user.is_authenticated %}
                  <div class="nav-collapse">
                  <ul class="nav">
                      <li class="dropdown label_menu">
                          <a href="#" class="dropdown-toggle title-link" data-toggle="dropdown">
                          {% if active_label %}
                              {{ active_label }}<span class="changed_indicator">*</span> <b class="caret"></b>
                          {% else %}
                              Labels <b class="caret"></b>
                          {% endif %}
                          </a>
                          <ul class="dropdown-menu">
                              <li><a href="/">Create new...</a></li>
                              <li class="divider"></li>
                              {% block label_actions %}{% endblock %}
                              {% if labels %}
                                  {% for label in labels %}
                                      {% if active_label == label.label_name %}
                                          <li class="active-item"><a href="/">{{ label.label_name }}</a></li>
                                      {% else %}
                                          <li><a href="/label/{{ label.label_name }}">{{ label.label_name }}</a></li>
                                      {% endif %}
                                  {% endfor %}
                              {% else %}
                                  <li class="disabled">No labels</li>
                              {% endif %}
                          </ul>
                      </li>
                      <li class="dropdown expectation_menu">
                          <a href="#" class="dropdown-toggle title-link" data-toggle="dropdown">
                          {% if active_expectation %}
                              {{ active_expectation }}<span class="changed_indicator">*</span> <b class="caret"></b>
                          {% else %}
                              Expectations <b class="caret"></b>
                          {% endif %}
                          </a>
                          <ul class="dropdown-menu">
                              <li><a href="/expectation/add/">Create new...</a></li>
                              <li class="divider"></li>
                              {% block expectation_actions %}{% endblock %}
                              {% if expectations %}
                                  {% for exp in expectations %}
                                      {% if active_expectation == exp.name %}
                                          <li class="active-item"><a href="/">{{ exp.name }}</a></li>
                                      {% else %}
                                          <li><a href="/expectation/{{ exp.name }}">{{ exp.name }}</a></li>
                                      {% endif %}
                                  {% endfor %}
                              {% else %}
                                  <li class="disabled">No expectations</li>
                              {% endif %}
                          </ul>
                      </li>
                  </ul>
                    {% block navbar %}{% endblock %}
                  </div>
              {% endif %}
              <div id="loading_indicator"><img src="{{ STATIC_URL }}img/ajax-loader.gif"></div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="content">
            {% block content %}{% endblock %}
        </div>
        <footer>
            <p><a href="http://github.com/monlog/monlog">Monlog @ GitHub</a></p>
        </footer>
    </div>
  </body>
</html>

monlog/log/templates/expectation.html
{% extends "base.html" %}
{% block navbar %}
<ul class="nav pull-right">
    <li class="divider-vertical"></li>
    <li class="expectation-refresh">
        <a href="#" onclick="event.preventDefault()" id="expectation-streaming-button">
            Refresh
        </a>
    </li>
</ul>
{% endblock %}
{% load verbatim %}
{% block expectation_actions %}
    {% if active_expectation %}
        <li><a href="#" class="expectation-save">Save<span class="changed_indicator">*</span></a></li>
        <li><a href="#save-new-expectation" data-toggle="modal">Save as...</a></li>
        <li><a href="/expectation/delete/{{ active_expectation }}">Remove</a></li>
    {% else %}
        <li><a href="#save-new-expectation" data-toggle="modal">Save as...</a></li>
    {% endif %}
  <li class="divider"></li>
{% endblock %}
{% block content %}
{% verbatim %}
    <script id="log_messages" type="text/html">
    {{#objects}}
    <tr class="sev-{{ severity }}{{#old}} old-data{{/old}}" id="msg-{{ id }}">
        <td><span class="label">{{ severity }}</span></td>
        <td><span class="">{{ datetime }}</span></td>
        <td><span class="">{{ application.username }}</span></td>
        <td><span class="">{{ server_ip }}</span></td>
        <td><a href="#" class="short_desc" onclick="event.preventDefault();" data-toggle="collapse" data-target="#details-msg-{{ id }}">{{ short_desc }}<i class="icon-expandable"></i></a></td>
    </tr>
    <tr>
        <td colspan="5" class="details">
            <div id="details-msg-{{ id }}" class="collapse long_desc"><pre>{{ long_desc }}</pre></div>
        </td>
    </tr>
    {{/objects}}
    </script>
{% endverbatim %}
<div class="well">
    <form class="monlog-control-form expectation-form" id="form-wrapper">
        <div class="control-group-wrapper">
            <div class="control-group">
                <label class="control-label">Deadline</label>
                <div class="control">
                    {{ eqf.deadline }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Tolerance</label>
                <div class="control">
                    {{ eqf.tolerance }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Repeat</label>
                <div class="control">
                    {{ eqf.repeat }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Amount of results</label>
                <div class="control">
                    {{ eqf.least_amount_of_results }}
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div class="control-group-wrapper">
            <div class="control-group">
                <label class="control-label">Severities</label>
                <div class="control">
                    <div class="multiple_select">
                        {{ eqf.severity__in }}
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Applications</label>
                <div class="control">
                    <div class="multiple_select">
                        {{ eqf.application__in }}
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Servers</label>
                <div class="control">
                    <div class="multiple_select">
                        {{ eqf.server_ip__in }}
                    </div>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>
    </form>
</div>
<div class="row-fluid">
    <div class="span12">
        <h3>Latest deadlines for {{ exp.name }}</h3><br />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table">
            <thead>
                <tr>
                    <th id="severity" class="sortable sorted-desc">Severity</th>
                    <th id="datetime" class="sortable sorted-desc sorted-active">Time</th>
                    <th id="application__username" class="sortable sorted-desc">Application</th>
                    <th id="server_ip" class="sortable sorted-desc">Server</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                <!-- no log messages loaded -->
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="save-new-expectation">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">x</a>
        <h3>Save new expectation</h3>
    </div>
    <div class="modal-body">
        <form id="save-expectation">
            <label class="control-expectation">Save as an expectation</label>
            <div class="controls">
                {{ eqf.name }}
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-primary expectation-save">Save</a>
        <a href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
</div>
<script type="text/javascript">
    var streamingMode = false;
    var expectationMode = true;
    var expectationName = {% if exp.name %}"{{ exp.name }}"{% else %}null{% endif %};
    var expectationID   = {% if exp.id   %} {{ exp.id }}   {% else %}-1  {% endif %};
</script>
<script type="text/javascript" src="{{ STATIC_URL }}js/api.js"></script>
<script type="text/javascript">
    var saveExpectation = function(event) {
        event.preventDefault();
        var query = $(".expectation-form").serialize();
        $.post("/expectation/save/", {
            csrfmiddlewaretoken : "{{ csrf_token }}",
            query: query,
            name: $("#id_name").val(),
            }, function(data) {
                window.location=data;
            }
            );
    };

    $(".expectation-save").click(saveExpectation);
    $("#save-expectation").submit(saveExpectation);

    $('.expectation-form input, .expectation-form select').change(function() {
        $(".expectation_menu .changed_indicator").show();
    });
    $(document).ready(function() {
        var datetimepickerFormat = {timeFormat: 'hh:mm:ss', dateFormat: 'yy-mm-dd', separator :'T'};
        $("#id_deadline").datetimepicker(datetimepickerFormat);
        $("th.sortable").append('<i class="icon-sortable"></i>');
        $("th.sortable").bind('click', function(event){
            if ($(this).hasClass('sorted-active')) {
                // already sorted on this column, so user wants to switch direction of sort
                $(this).toggleClass('sorted-desc').toggleClass('sorted-asc');
            } else {
                $("th.sortable").removeClass('sorted-active');
                $(this).toggleClass('sorted-active');
            }

            var ordering_param = ($(this).hasClass('sorted-desc') ? '-' : '') + this.id;
            $('form.filters input[name="order_by"]').attr('value', ordering_param);
            $('form.filters input[name="order_by"]').change();
        });
        $("#expectation-streaming-button").click(function() {
            requestLogMessages(getFormData(),updateLogTable);
        });
    });
</script>
{% endblock %}

monlog/log/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Monlog</h1>
{% endblock %}

monlog/log/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Login</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit" class="btn btn-primary">Login</button></p>
</form>
{% endblock %}